version: '3.3'

networks:
  default:
    external:
      name: nginx-net

volumes:
  mysql_data:

services:

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/wp.ini
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      LETSENCRYPT_HOST: wordpress.chrisroc.co
      LETSENCRYPT_EMAIL: chris.rocco7@gmail.com
      VIRTUAL_HOST: wordpress.chrisroc.co
